name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: myfaith/iptv

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t ${IMAGE_NAME} .

      - name: Log into registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          IMAGE_ID=${IMAGE_NAME}
          docker push ${IMAGE_ID}
